### ISSUE TITLE
Is that possible to provide the pretrained model on Chairs or Chairs-Things3D ?

### ISSUE THREAD

**Issue by xuanlongORZ** [lhao0301/pytorch-liteflownet3#1]
Thank you very much for the re-implementation. 
I wonder if it is possible to provide also the pre-trained model which trained on Chairs only or on Chairs then Things3D ?
Thank you again.

**Comment by lhao0301** [comment]
I haven't trained the model from scratch and I just convert the official pre-trained caffe model to pytorch. The models trained on Chairs or Chairs+Things3D are not released in the official [repo.](https://github.com/twhui/LiteFlowNet3) 
Maybe u could contact the author of Liteflownet3 for the pre-trained models.
