### ISSUE TITLE
How to warp the image with optical flow (.flo)?

### ISSUE THREAD

**Issue by caogaofeng** [lhao0301/pytorch-liteflownet3#2]
Thank you for your reimplementation of LiteFlowNet3 using PyTorch, it is very useful to me. However, I don’t know how to warp the image using the output optical flow file (.flo).  
I use the next flow_warp function, but it does not work.

```
def flow_warp(x, flow, padding_mode='zeros'):
    """Warp an image or feature map with optical flow
    Args:
        x (Tensor): size (n, c, h, w)
        flow (Tensor): size (n, 2, h, w), values range from -1 to 1 (relevant to image width or height)
        padding_mode (str): 'zeros' or 'border'

    Returns:
        Tensor: warped image or feature map
    """
    assert x.size()[-2:] == flow.size()[-2:]
    n, _, h, w = x.size()
    x_ = torch.arange(w).view(1, -1).expand(h, -1)
    y_ = torch.arange(h).view(-1, 1).expand(-1, w)
    grid = torch.stack([x_, y_], dim=0).float().cuda()
    grid = grid.unsqueeze(0).expand(n, -1, -1, -1)
    grid[:, 0, :, :] = 2 * grid[:, 0, :, :] / (w - 1) - 1
    grid[:, 1, :, :] = 2 * grid[:, 1, :, :] / (h - 1) - 1
    grid += flow
    grid = grid.permute(0, 2, 3, 1)
    return torch.nn.functional.grid_sample(x, grid)
```

**Comment by caogaofeng** [comment]
`numpy.array([ 80, 73, 69, 72 ], numpy.uint8).tofile(objOutput)`  What is the meaning of this code?

**Comment by lhao0301** [comment]
> `numpy.array([ 80, 73, 69, 72 ], numpy.uint8).tofile(objOutput)` What is the meaning of this code?

It's used for sanity check. You can refer [here](https://vision.middlebury.edu/flow/code/flow-code/README.txt) for more details of the `flo` file.

**Comment by lhao0301** [comment]
What's the detailed problem of `It does not work`? 
You can just refer to the [backwarp_function](https://github.com/lhao0301/pytorch-liteflownet3/blob/f3dee2e656d2b6ac386eeb5a252dbe1afa518c3c/run.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L38).
